### ISSUE TITLE
Use cachix?

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-extra-plugins#40]
Currently, CI takes way longer time ~3 mins/run. It could get shorter if I use cachix. By the way, cachix pricing shows JPY 10/month, which is equal to USD 0.087/month (at 2021-12-30). Isn't it a mistake?

**Comment by bandithedoge** [comment]
Cachix has free public caches for open source projects limited to 5GB which should be more than enough for a bunch of Vim plugins.

**Comment by m15a** [comment]
> Cachix has free public caches for open source projects limited to 5GB

I didn't know that, thanks!
