### ISSUE TITLE
Broken overlay due to `ataraxis-lua` 

### ISSUE THREAD

**Issue by adgai19** [m15a/nixpkgs-vim-extra-plugins#91]
[The latest commit](https://github.com/m15a/nixpkgs-vim-extra-plugins/commit/da34121cc07554ee2f3e5a2eaea012cf4dc1df75) has two derivations for `ataraxis-lua` and as a result, the build breaks with error 
```
error: attribute 'ataraxis-lua' already defined at /nix/store/fgji64na35q0kikbfl7gr1gpj0wimhwd-source/pkgs/vim-plugins.nix:1887:3

       at /nix/store/fgji64na35q0kikbfl7gr1gpj0wimhwd-source/pkgs/vim-plugins.nix:1900:3:

         1899|   };
         1900|   ataraxis-lua = buildVimPluginFrom2Nix {
             |   ^
         1901|     pname = "ataraxis-lua";
``` 
I am sorry if I named any term wrong, I am new to nix and still learning.

**Comment by m15a** [comment]
Thanks for reporting! This is fixed by #92.
Sometimes duplicated plugins appear because plugin authors move/rename their repositories, and they have to be fixed manually.
